/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package edu.ulima.datos.proyecto.bean;

/**
 *
 * @author jteve
 */
public class FECHA extends PEDIDO{
    private final String FECHA_SOLICITUD, FECHA_ENTREGA;

    public FECHA(String FECHA_SOLICITUD, String FECHA_ENTREGA, int NUMERO_ORDEN, String REQUERIMIENTOS, String ESTADO_PEDIDO, String ENCARGADO_ENVIO, int NUMERO_SEGUIMIENTO, String CODIGO_CLIENTE, String NOMBRE_CLIENTE, String DIRECCION_CLIENTE, String CORREO_CLIENTE, int TELEFONO_CLIENTE, int RUC, String CODIGO_REPRESENTANTE, String NOMBRE_REPRESENTANTE, String CORREO_REPRESENTANTE, int TELEFONO_REPRESENTANTE, String CODIGO_COTIZACION, float FACTURA_TOTAL, String CODIGO_PROVEEDOR, String NOMBRE_PROVEEDOR, String CORREO_PROVEEDOR, String PAIS, String CIUDAD, int TELEFONO_PROVEEDOR, String CODIGO_PRODUCTO, String TIPO, String UNIDAD_MEDIDA, String DESCRIPCION, int CANTIDAD, float PRECIO_UNITARIO) {
        super(NUMERO_ORDEN, REQUERIMIENTOS, ESTADO_PEDIDO, ENCARGADO_ENVIO, NUMERO_SEGUIMIENTO, CODIGO_CLIENTE, NOMBRE_CLIENTE, DIRECCION_CLIENTE, CORREO_CLIENTE, TELEFONO_CLIENTE, RUC, CODIGO_REPRESENTANTE, NOMBRE_REPRESENTANTE, CORREO_REPRESENTANTE, TELEFONO_REPRESENTANTE, CODIGO_COTIZACION, FACTURA_TOTAL, CODIGO_PROVEEDOR, NOMBRE_PROVEEDOR, CORREO_PROVEEDOR, PAIS, CIUDAD, TELEFONO_PROVEEDOR, CODIGO_PRODUCTO, TIPO, UNIDAD_MEDIDA, DESCRIPCION, CANTIDAD, PRECIO_UNITARIO);
        this.FECHA_SOLICITUD = FECHA_SOLICITUD;
        this.FECHA_ENTREGA = FECHA_ENTREGA;
    }

    public String getFECHA_SOLICITUD() {
        return FECHA_SOLICITUD;
    }

    public String getFECHA_ENTREGA() {
        return FECHA_ENTREGA;
    }
    
    
}
