--PROCEDURE
CREATE OR REPLACE PROCEDURE REGISTRAR_CLIENTE(NOMBRE CLIENTE.NOMBRE_CLIENTE%TYPE, DIRECCION CLIENTE.DIRECCION_CLIENTE%TYPE, TELEFONO CLIENTE.TELEFONO_CLIENTE%TYPE, 
CORREO CLIENTE.CORREO_CLIENTE%TYPE, RUC CLIENTE.RUC_CLIENTE%TYPE)
AS
CODIGO CLIENTE.CODIGO_CLIENTE%TYPE;
BEGIN
    SELECT NVL(MAX(CODIGO), 1000) + 1 INTO CODIGO FROM CLIENTE;
    
    INSERT INTO CLIENTE VALUES (CODIGO, NOMBRE, DIRECCION, TELEFONO, CORREO, RUC);
END;

CREATE OR REPLACE PROCEDURE REGISTRAR_PEDIDO(ENCARGADO PEDIDO.ENCARGADO_ENVIO%TYPE, NUMSEGUIMIENTO PEDIDO.NUMERO_SEGUIMIENTO%TYPE, REQ PEDIDO.REQUERIMIENTOS%TYPE, ESTPED PEDIDO.ESTADO_PEDIDO%TYPE)
AS
NUMORDEN PEDIDO.NUMERO_ORDEN%TYPE;
BEGIN
    SELECT NVL(MAX(NUMORDEN), 0) + 1 INTO NUMORDEN FROM PEDIDO;
    
    INSERT INTO PEDIDO VALUES (NUMORDEN, ENCARGADO, NUMSEGUIMIENTO, REQ, ESTPED);
END;