CREATE TABLE PRODUCTO
(
  NOMBRE_PRODUCTO VARCHAR2(50),
  CODIGO_PRODUCTO VARCHAR2(30) PRIMARY KEY,
  TIPO VARCHAR2(30),
  CANTIDAD NUMBER(9),
  PRECIO_UNITARIO NUMBER(9),
  UNIDAD_MEDIDA VARCHAR2(30),
  DESCRIPCION VARCHAR2(100)
  );

CREATE TABLE PEDIDO
(
  NUMERO_ORDEN NUMBER(18) PRIMARY KEY,
  ENCARGADO_ENVIO VARCHAR2(30),
  NUMERO_SEGUIMIENTO VARCHAR2(30) UNIQUE,
  REQUERIMIENTOS VARCHAR2(500) UNIQUE,
  ESTADO_PEDIDO VARCHAR2(20)
);

CREATE TABLE CLIENTE
(
  NOMBRE_CLIENTE VARCHAR2(50),
  DIRECCION_CLIENTE VARCHAR2(100),
  CODIGO_CLIENTE VARCHAR2(30) PRIMARY KEY,
  TELEFONO_CLIENTE NUMBER(9),
  CORREO_CLIENTE VARCHAR2(50),
  RUC_CLIENTE NUMBER(11) UNIQUE,
  NUMERO_ORDEN REFERENCES PEDIDO
);

CREATE TABLE PROVEEDOR
(
  NOMBRE_PROVEEDOR VARCHAR2(50),
  CODIGO_PROVEEDOR VARCHAR2(30) PRIMARY KEY,
  CORREO_PROVEEDOR VARCHAR2(50),
  TELEFONO_PROVEEDOR NUMBER(9),
  PAIS VARCHAR2(30),
  CIUDAD VARCHAR2(30),
  CODIGO_PRODUCTO REFERENCES PRODUCTO
);

CREATE TABLE REPRESENTANTE
(
  NOMBRE_REPRESENTANTE VARCHAR2(50),
  CODIGO_REPRESENTANTE VARCHAR2(30) PRIMARY KEY,
  CORREO_REPRESENTANTE VARCHAR2(50),
  TELEFONO_REPRESENTANTE NUMBER(9),
  CODIGO_CLIENTE REFERENCES CLIENTE
);

CREATE TABLE COTIZACION
(
  CODIGO_COTIZACION VARCHAR2(30) PRIMARY KEY,
  FACTURA_TOTAL NUMBER(6,2),
  CODIGO_REPRESENTANTE REFERENCES REPRESENTANTE,
  CODIGO_PROVEEDOR REFERENCES PROVEEDOR,
  CODIGO_PRODUCTO REFERENCES PRODUCTO
);

CREATE TABLE FECHA
(
  FECHA_SOLICITUD DATE,
  FECHA_ENTREGA DATE,
  NUMERO_ORDEN REFERENCES PEDIDO
);